version: "3.7"

services:

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: miniautorizador
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./scripts/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql:ro
